In [ ]:
# Blok 1
import pandas as pd

# Membaca setiap file CSV ke dalam DataFrame
try:
    items_df = pd.read_csv('olist_order_items_dataset.csv')
    orders_df = pd.read_csv('olist_orders_dataset.csv')
    products_df = pd.read_csv('olist_products_dataset.csv')
    customers_df = pd.read_csv('olist_customers_dataset.csv')
    payments_df = pd.read_csv('olist_order_payments_dataset.csv')
    print("Semua file berhasil dimuat.")
except FileNotFoundError as e:
    print(f"Error: Pastikan file {e.filename} sudah di-upload ke Colab.")

Semua file berhasil dimuat.

In [ ]:
# Blok 2
# Menggabungkan tabel item dengan tabel pesanan
# 'inner' join berarti hanya baris yang punya pasangan order_id di kedua tabel yang akan diambil
merged_df = pd.merge(items_df, orders_df, on='order_id', how='inner')

print("Ukuran data setelah penggabungan pertama:", merged_df.shape)
merged_df.head()

Ukuran data setelah penggabungan pertama: (112650, 14)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00

In [ ]:
# Blok 5
# Menggabungkan dengan tabel produk
merged_df = pd.merge(merged_df, products_df, on='product_id', how='inner')

print("Ukuran data setelah penggabungan kedua:", merged_df.shape)
merged_df.head()

Ukuran data setelah penggabungan kedua: (112650, 22)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,order_delivered_customer_date,order_estimated_delivery_date,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,2017-09-20 23:43:48,2017-09-29 00:00:00,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,2017-05-12 16:04:24,2017-05-15 00:00:00,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,2018-01-22 13:19:16,2018-02-05 00:00:00,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,2018-08-14 13:32:39,2018-08-20 00:00:00,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,2017-03-01 16:42:31,2017-03-17 00:00:00,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0

In [ ]:
# Blok 4
# Langsung gabungkan hasil dari Blok 3 dengan tabel pelanggan
# karena 'customer_id' sudah ada di merged_df
merged_df = pd.merge(merged_df, customers_df, on='customer_id', how='inner')

print("Ukuran data setelah penggabungan ketiga:", merged_df.shape)
merged_df.head()

Ukuran data setelah penggabungan ketiga: (112650, 26)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,598.0,4.0,650.0,28.0,9.0,14.0,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,239.0,2.0,30000.0,50.0,30.0,40.0,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,695.0,2.0,3050.0,33.0,13.0,33.0,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,480.0,1.0,200.0,16.0,10.0,15.0,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,409.0,1.0,3750.0,35.0,40.0,30.0,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP

In [ ]:
# Blok 5
# Terakhir, gabungkan dengan tabel pembayaran
final_merged_df = pd.merge(merged_df, payments_df, on='order_id', how='inner')

print("Ukuran data akhir:", final_merged_df.shape)
# Tampilkan beberapa kolom penting saja untuk verifikasi
final_merged_df[['order_id', 'product_category_name', 'customer_city', 'payment_type', 'price', 'payment_value']].head()

Ukuran data akhir: (117601, 30)

,order_id,product_category_name,customer_city,payment_type,price,payment_value
0,00010242fe8c5a6d1ba2dd792cb16214,cool_stuff,campos dos goytacazes,credit_card,58.90,72.19
1,00018f77f2f0320c557190d7a144bdd3,pet_shop,santa fe do sul,credit_card,239.90,259.83
2,000229ec398224ef6ca0657da4fc703e,moveis_decoracao,para de minas,credit_card,199.00,216.87
3,00024acbcdf0a6daa1e931b038114c75,perfumaria,atibaia,credit_card,12.99,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,ferramentas_jardim,varzea paulista,credit_card,199.90,218.04

In [ ]:
final_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117601 entries, 0 to 117600
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117601 non-null  object
 1   order_item_id                  117601 non-null  int64
 2   product_id                     117601 non-null  object
 3   seller_id                      117601 non-null  object
 4   shipping_limit_date            117601 non-null  object
 5   price                          117601 non-null  float64
 6   freight_value                  117601 non-null  float64
 7   customer_id                    117601 non-null  object
 8   order_status                   117601 non-null  object
 9   order_purchase_timestamp       117601 non-null  object
 10  order_approved_at              117586 non-null  object
 11  order_delivered_carrier_date   116356 non-null  object
 12  order_delivered_customer_date  115034 non-null  object
 13  order_estimated_delivery_date  117601 non-null  object
 14  product_category_name          115903 non-null  object
 15  product_name_lenght            115903 non-null  float64
 16  product_description_lenght     115903 non-null  float64
 17  product_photos_qty             115903 non-null  float64
 18  product_weight_g               117581 non-null  float64
 19  product_length_cm              117581 non-null  float64
 20  product_height_cm              117581 non-null  float64
 21  product_width_cm               117581 non-null  float64
 22  customer_unique_id             117601 non-null  object
 23  customer_zip_code_prefix       117601 non-null  int64
 24  customer_city                  117601 non-null  object
 25  customer_state                 117601 non-null  object
 26  payment_sequential             117601 non-null  int64
 27  payment_type                   117601 non-null  object
 28  payment_installments           117601 non-null  int64
 29  payment_value                  117601 non-null  float64
dtypes: float64(10), int64(4), object(16)
memory usage: 26.9+ MB

In [ ]:
# Blok 6
# Cek jumlah data kosong di setiap kolom
print("Jumlah data kosong sebelum dibersihkan:")
final_merged_df.isnull().sum()

Jumlah data kosong sebelum dibersihkan:

order_id                            0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1245
order_delivered_customer_date    2567
order_estimated_delivery_date       0
product_category_name            1698
product_name_lenght              1698
product_description_lenght       1698
product_photos_qty               1698
product_weight_g                   20
product_length_cm                  20
product_height_cm                  20
product_width_cm                   20
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
payment_sequential                  0
payment_type                        0
payment_installments                0
payment_value                       0
dtype: int64

In [ ]:
# Blok 7
# Kolom yang akan diubah tipe datanya
kolom_tanggal = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

# Loop untuk mengubah setiap kolom tanggal menjadi tipe datetime
for kolom in kolom_tanggal:
    final_merged_df[kolom] = pd.to_datetime(final_merged_df[kolom], errors='coerce')

# Cek kembali tipe data untuk memastikan sudah berubah
final_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117601 entries, 0 to 117600
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117601 non-null  object
 1   order_item_id                  117601 non-null  int64
 2   product_id                     117601 non-null  object
 3   seller_id                      117601 non-null  object
 4   shipping_limit_date            117601 non-null  object
 5   price                          117601 non-null  float64
 6   freight_value                  117601 non-null  float64
 7   customer_id                    117601 non-null  object
 8   order_status                   117601 non-null  object
 9   order_purchase_timestamp       117601 non-null  datetime64[ns]
 10  order_approved_at              117586 non-null  datetime64[ns]
 11  order_delivered_carrier_date   116356 non-null  datetime64[ns]
 12  order_delivered_customer_date  115034 non-null  datetime64[ns]
 13  order_estimated_delivery_date  117601 non-null  datetime64[ns]
 14  product_category_name          115903 non-null  object
 15  product_name_lenght            115903 non-null  float64
 16  product_description_lenght     115903 non-null  float64
 17  product_photos_qty             115903 non-null  float64
 18  product_weight_g               117581 non-null  float64
 19  product_length_cm              117581 non-null  float64
 20  product_height_cm              117581 non-null  float64
 21  product_width_cm               117581 non-null  float64
 22  customer_unique_id             117601 non-null  object
 23  customer_zip_code_prefix       117601 non-null  int64
 24  customer_city                  117601 non-null  object
 25  customer_state                 117601 non-null  object
 26  payment_sequential             117601 non-null  int64
 27  payment_type                   117601 non-null  object
 28  payment_installments           117601 non-null  int64
 29  payment_value                  117601 non-null  float64
dtypes: datetime64[ns](5), float64(10), int64(4), object(11)
memory usage: 26.9+ MB

In [ ]:
# Blok 8
# 1. Membuat kolom 'tahun' dan 'bulan' dari tanggal pembelian
final_merged_df['purchase_year'] = final_merged_df['order_purchase_timestamp'].dt.year
final_merged_df['purchase_month'] = final_merged_df['order_purchase_timestamp'].dt.month
final_merged_df['purchase_month_name'] = final_merged_df['order_purchase_timestamp'].dt.strftime('%B') # Nama bulan (e.g., January)

# 2. Menghitung durasi pengiriman dalam hari
final_merged_df['delivery_duration'] = (final_merged_df['order_delivered_customer_date'] - final_merged_df['order_purchase_timestamp']).dt.days

# Tampilkan beberapa kolom baru untuk verifikasi
final_merged_df[['order_purchase_timestamp', 'purchase_year', 'purchase_month_name', 'delivery_duration']].head()

,order_purchase_timestamp,purchase_year,purchase_month_name,delivery_duration
0,2017-09-13 08:59:02,2017,September,7.0
1,2017-04-26 10:53:06,2017,April,16.0
2,2018-01-14 14:33:31,2018,January,7.0
3,2018-08-08 10:00:35,2018,August,6.0
4,2017-02-04 13:57:51,2017,February,25.0

In [ ]:
final_merged_df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value,purchase_year,purchase_month,purchase_month_name,delivery_duration
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,campos dos goytacazes,RJ,1,credit_card,2,72.19,2017,9,September,7.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,santa fe do sul,SP,1,credit_card,3,259.83,2017,4,April,16.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,para de minas,MG,1,credit_card,5,216.87,2018,1,January,7.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,atibaia,SP,1,credit_card,2,25.78,2018,8,August,6.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,varzea paulista,SP,1,credit_card,3,218.04,2017,2,February,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117596,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,...,sao luis,MA,1,boleto,1,343.40,2018,4,April,17.0
117597,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,...,curitiba,PR,1,boleto,1,386.53,2018,7,July,9.0
117598,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,...,sao paulo,SP,1,credit_card,3,116.85,2017,10,October,4.0
117599,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,...,vinhedo,SP,1,credit_card,3,64.71,2017,8,August,1.0
117600,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,...,botucatu,SP,1,credit_card,1,55.79,2018,6,June,5.0

In [ ]:
# Terakhir Metode Ekspor dengan Potongan (Chunking) dan Jeda Waktu

# Import library yang dibutuhkan
import pandas as pd
from google.colab import auth
from google.auth import default
import gspread
import time # library 'time' untuk memberi jeda
import numpy as np # Import numpy untuk menangani NaN

# Lakukan autentikasi
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Buka spreadsheet dan pilih sheet pertama
nama_spreadsheet = "Olist E-commerce Data Mart"
spreadsheet = gc.open(nama_spreadsheet)
worksheet = spreadsheet.sheet1

# --- Logika Pengiriman Bertahap ---

# API Google Sheets tidak bisa menerima nilai seperti NaN atau inf.
# Kita harus mengubahnya menjadi format yang bisa diterima, seperti teks kosong ('').

final_merged_df = final_merged_df.replace([np.inf, -np.inf], np.nan) # Ubah nilai tak terhingga menjadi nilai NaN
final_merged_df = final_merged_df.fillna('') # Ubah semua nilai NaN menjadi teks kosong ('')

for col in final_merged_df.select_dtypes(include=['datetime64[ns]']).columns:
    final_merged_df[col] = final_merged_df[col].astype(str)

data_to_export = [final_merged_df.columns.values.tolist()] + final_merged_df.values.tolist()

# Tentukan ukuran potongan
chunk_size = 10000
total_rows = len(data_to_export)

print(f"Total baris yang akan dikirim: {total_rows-1}. Ukuran potongan: {chunk_size} baris.")
print("Memulai proses pengiriman... Ini akan memakan waktu beberapa menit.")

# Loop ini akan berjalan dari baris ke-0 hingga baris terakhir, dengan loncatan sebesar ukuran potongan
for i in range(0, total_rows, chunk_size):
    # Ambil potongan data
    chunk = data_to_export[i:i + chunk_size]

    # Kirim potongan ke worksheet
    worksheet.append_rows(chunk, value_input_option='USER_ENTERED')

    # Tampilkan progres
    # Adjust progress print to show the range of rows being sent
    print(f"Berhasil mengirim baris {i} hingga {min(i + chunk_size -1, total_rows-1)}...")


    # Beri jeda waktu 1.5 detik untuk "mengistirahatkan" API
    time.sleep(1.5)

print("\nSeluruh data berhasil diekspor ke Google Sheet.")

Spreadsheet sudah dibersihkan dan siap diisi.
Total baris yang akan dikirim: 117601. Ukuran potongan: 10000 baris.
Memulai proses pengiriman... Ini akan memakan waktu beberapa menit.
Berhasil mengirim baris 0 hingga 9999...
Berhasil mengirim baris 10000 hingga 19999...
Berhasil mengirim baris 20000 hingga 29999...
Berhasil mengirim baris 30000 hingga 39999...
Berhasil mengirim baris 40000 hingga 49999...
Berhasil mengirim baris 50000 hingga 59999...
Berhasil mengirim baris 60000 hingga 69999...
Berhasil mengirim baris 70000 hingga 79999...
Berhasil mengirim baris 80000 hingga 89999...
Berhasil mengirim baris 90000 hingga 99999...
Berhasil mengirim baris 100000 hingga 109999...
Berhasil mengirim baris 110000 hingga 117601...

SELAMAT! Seluruh data berhasil diekspor ke Google Sheet.